# ===== Listener MQTT 1883 (clair) - authentification requise =====
listener 1883

# ===== Listener MQTTS 8883 (TLS) =====
listener 8883
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2

# ===== Securite =====
allow_anonymous true
password_file /mosquitto/config/passwd

#persistence true
#persistence_location /mosquitto/data/
